player/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import home, new_invitation

app_name = 'player'

urlpatterns = [
    path('home', home, name="home"),
    path('login', LoginView.as_view(template_name="player/login.html"), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('new_invitation', new_invitation, name="new_invitation")

]

tictactoe/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import welcome

urlpatterns = [
    path('admin/', admin.site.urls),
    path('player/', include('player.urls')),
    path('', welcome, name="welcome")
]

gameplay/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User

GAME_STATUS_CHOICES = (
    ('F', 'First Player To Move'),
    ('S', 'Second Player To Move'),
    ('W', 'First Player Wins'),
    ('L', 'Second Player Wins'),
    ('D', 'Draw'),

)

class GamesQuerySet(models.QuerySet):
    def games_for_user(self, user):
        return self.filter(
            Q(first_player=user) | Q(second_player=user)
        )

    def active(self):
        return self.filter(
            Q(status="F") | Q(status="S")
        )

class Game(models.Model):
    first_player = models.ForeignKey(User, related_name="games_first_player", on_delete=models.CASCADE)
    second_player = models.ForeignKey(User, related_name="games_second_player", on_delete=models.CASCADE)
    start_time = models.DateTimeField(auto_now_add=True)
    last_active = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, default="F", choices=GAME_STATUS_CHOICES)

    objects = GamesQuerySet.as_manager()

    def __str__(self):
        return "{0} vs {1}".format(self.first_player, self.second_player)

class Move(models.Model):
    x = models.IntegerField()
    y = models.IntegerField()
    comment = models.CharField(max_length=300, blank=True)
    by_first_player = models.BooleanField()

    game = models.ForeignKey(Game, on_delete=models.CASCADE)

player/models.py
from django.contrib.auth.models import User
from django.db import models

class Invitation(models.Model):
    from_user = models.ForeignKey(User, related_name="invitations_sent", on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name="invitations_received", on_delete=models.CASCADE)
    message = models.CharField(max_length=300)
    timestamp = models.DateTimeField(auto_now_add=True)

player/forms.py
from django.forms import ModelForm

from player.models import Invitation


class InvitationForm(ModelForm):
    class Meta:
        model = Invitation
        exclude = ('from_user', 'timestamp')

gameplay/views.py
from django.shortcuts import render

# Create your views here.

player/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from gameplay.models import Game
from player.forms import InvitationForm


@login_required
def home(request):
    my_games = Game.objects.games_for_user(request.user.id)
    active_games = my_games.active()

    # Important to understand hwo many queries are actually ran for this
    # Lazy query sets are only updated when they actually get used

    # all_my_games = list(games_first_player) + \
    #                 list(games_second_player)

    return render(request, "player/home.html", {'games': active_games})

@login_required
def new_invitation(request):
    if request.method == 'POST':
        form = InvitationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('player:home')
    else:
        form = InvitationForm()
    return render(request, "player/new_invitation.html", {'form': form})

tictactoe/views.py
from django.shortcuts import render, redirect


def welcome(request):
    if request.user.is_authenticated:
        return redirect('player_home')
    else:
        return render(request, 'tictactoe/welcome.html')

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
        <style>
            body {
                padding-top: 70px;
                padding-bottom: 20px;
                padding-left: 83px;
            }
        </style>
        <link rel="stylesheet" href={% static 'css/bootstrap-theme.min.css' %}>
        <link rel="stylesheet" href={% static 'css/main.css' %}>

        <script src={% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}></script>
    </head>
    <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="../static">Django Fundamentals</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'player:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'player:login' %}">Login</a></li>
            {% endif %}
        </ul>
      </div>
    </nav>

    <div>
        {% block content %}
        {% endblock %}
    </div>


        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src={% static 'js/vendor/jquery-1.11.2.min.js' %}><\/script>')</script>

        <script src={% static 'js/vendor/bootstrap.min.js' %}></script>

        <script src={% static '/js/main.js' %}></script>
    </body>
</html>

templates/player/home.html
{%  extends 'base.html' %}

{% block title %}
Welcome
{% endblock %}

{%  block content %}
    <h1>Welcome, {{ user.username }}</h1>
    These are your active games:

    <ul>
        {%  for g in games %}
            <li>Game {{ g.id }}: {{ g.first_player }} vs {{ g.second_player }}</li>
        {%  endfor %}
    </ul>

    <a href="{% url 'player:new_invitation' %}">
        Invite another user to play a game
    </a>
{% endblock %}

templates/player/login.html
{%  extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{%  block content %}
    <form role="form" action="{% url 'player:login' %}" method="post" >
        {% csrf_token %}

        <p>Please login</p>

        {{ form }}

        <button type="submit" class="btn btn-success">Sign in</button>
    </form>
{% endblock %}

templates/player/new_invitation.html
{%  extends 'base.html' %}

{% block title %}
    New Invitation
{% endblock %}

{%  block content %}
    <form action="{% url 'player:new_invitation' %}" method="post">

        {{ form }}

        <button type="submit">Send the invitation</button>
    </form>
{% endblock %}

templates/tictactoe/welcome.html
{%  extends 'base.html' %}

{% block title %}
Welcome
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
            <h1>Hello, world!</h1>
            <p>Let's play tictactoe</p>
        </div>
    </div>
{% endblock %}